5.1
AlinaRodina99/semester4 pull request #13
Opened 2020-08-25 14:03 UTC by AlinaRodina99

2020-08-25 16:46 UTC, yurii-litvinov requested changes

2020-08-25 16:46 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Computer.fs
> +          | _ -> 0.5
Я б сделал отдельный класс для операционной системы и это свойство бы там разместил, тут оно как-то не в тему (хотя это minor issue, можно не править).

2020-08-25 16:46 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Computer.fs
> +          let rnd = new Random()
А вот создавать Random каждый раз точно неправильно --- во-первых, он инициализируется по умолчанию системным таймером, так что если несколько Infect-ов произошли в одну миллисекунду, результат будет одинаковым. Во-вторых, и в главных, на самом деле, это каждый раз выделение памяти на куче, за что сборщик мусора спасибо не скажет. Достаточно одного рандома на всю программу обычно, просто передавайте его в конструктор.

2020-08-25 16:46 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Computer.fs
> +          if randomValue <  probability then true else false
Ой :)

2020-08-25 16:46 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Computer.fs
> +         and set (value) = isInfected <- value
Это, кажется, могло бы быть автоматическим свойством

2020-08-25 16:46 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Network.fs
> +             if matrix.[i, j] = true && (computers.Item i).IsInfected then
`matrix.[i, j] = true` --- это же просто `matrix.[i, j]`

2020-08-25 16:46 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Network.fs
> +                  else ()
Это можно не писать

2020-08-25 16:46 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Network.fs
> +                  (computers.Item j).IsInfected <- true
А так может получиться, что один компьютер всю сеть за один ход заразит --- сначала заражает один, затем вновь заражённый тут же, на этом ходу, заражает другой и т.д., что противоречит условию задачи. Надо как-то следить за теми, кто был заражён на этом ходу, следовательно, ещё не опасен.

2020-08-27 11:44 UTC, yurii-litvinov requested changes

2020-08-27 11:44 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Computer.fs
> +     let random = new Random()
Зачем же каждому компьютеру свой рандом? Если есколько компьютеров создано одновременно, они будут одинаково себя вести, что нехорошо

2020-08-27 11:44 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Computer.fs
> +          if randomValue < probability then true else false
Кто-то не знает булевой алгебры? :) Это же просто `randomValue < probability`

2020-08-27 11:44 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Network.fs
> +     let lentghOfComputerList = List.length computers
Опечатка

2020-08-27 11:44 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Network.fs
> +             if matrix.[i, j] && (computers.Item i).IsInfected && not (computers.Item i).NewlyInfected then
`(computers.Item i).IsInfected && not (computers.Item i).NewlyInfected` --- а вот если бы у Computer был метод CanInfect или что-то такое, то, с одной стороны, не надо было бы писать такие длинные и непонятные условия, и с другой стороны, не было бы ощущения, что Network нарушает инкапсуляцию Computer

2020-08-27 11:44 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Network.fs
> +               let os_j = new OperationSystem((computers.Item j).OperationSystem)
camelCase нужен. И тут происходит нечто ужасное с точки зрения сборки мусора, подумайте, как это сделать адекватно.

2020-08-29 13:00 UTC, yurii-litvinov requested changes
Да, вот теперь почти всё хорошо и правильно, надо только немного архитектурной красоты навести. Почти зачтена :)

2020-08-29 13:00 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Computer.fs
> +         and set (value) = isInfected <- value
Это надо либо поправить, либо написать, почему Вы это править не хотите. В продакшене, когда Вам пишут замечание на кодревью, оставить половину без внимания очень непрофессионально

2020-08-29 13:00 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Computer.fs
> +         and set (value) = newlyInfected <- value
То же самое, геттер с сеттером, которые ничего нового, кажется, не привносят, могло бы быть `member val NewlyInfected = false with get; set`

2020-08-29 13:00 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Network.fs
> +             List.iter (fun (x : Computer) -> if x.NewlyInfected then x.NewlyInfected <- false) computers
Вместо `if x.NewlyInfected then x.NewlyInfected <- false` я бы написал что-то вроде `x.ClearNewlyInfected ()`. Сбросить флаг может (и должен) сам компьютер, это его дело.

2020-08-29 13:00 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Network.fs
> +                  (computers.Item j).NewlyInfected <- true
Ну и тут, `(computers.Item j).Infect ()`. Это ж азы инкапсуляции.

2020-08-29 14:43 UTC, AlinaRodina99 commented on homework5/5.1/5.1/5.1/Computer.fs
> +         and set (value) = newlyInfected <- value
Просто я там в методе CanInfect использую переменные isInfected и newlyInfected, с автоматическими свойствами переменные не изменялись, и тесты не проходили

2020-08-29 16:05 UTC, AlinaRodina99 commented on homework5/5.1/5.1/5.1/Computer.fs
> +         and set (value) = newlyInfected <- value
Я переделывала с автоматическим свойством, но тесты так не проходили, там я проверяю по свойству, заразился компьютер или нет, то есть IsInfected  как был false в начале, так и остался, а с геттером и сеттером все работает.

2020-08-29 16:09 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Computer.fs
> +         and set (value) = newlyInfected <- value
Так естественно, переменные надо удалить и менять сами свойства :)

2020-08-29 16:31 UTC, AlinaRodina99 commented on homework5/5.1/5.1/5.1/Computer.fs
> +         and set (value) = newlyInfected <- value
Да, я так и пробовала делать, убрав переменные, но когда я пыталась написать метод CanInfect, используя свойства IsInfected и NewlyInfected, мне выдавалась ошибка, что таких свойств не существует, он не видел почему - то, а переменные видны были

2020-08-29 18:14 UTC, yurii-litvinov commented on homework5/5.1/5.1/5.1/Computer.fs
> +         and set (value) = newlyInfected <- value
Ваша схема рассуждения сводится к "Мне говорят сделать вот так, у меня не вышло --- конечно же не потому, что я что-то не так делаю, а, нууу, просто не вышло. Погуглить? Нет! Спросить у препода? Нафиг. Почему бы просто не забить, может, прокатит" :)

Подсказка:
```fsharp
     member this.Infect () =
         this.IsInfected <- true
         newlyInfected <- true
```

2020-08-30 14:13 UTC, AlinaRodina99 commented on homework5/5.1/5.1/5.1/Computer.fs
> +         and set (value) = newlyInfected <- value
Правда почему - то не подумала спросить)) Показалось, что другого решения нет, спасибо ! Теперь все работает

2020-08-30 15:59 UTC, yurii-litvinov approved these changes
Да, вот теперь всё ок, зачтена :)

2022-07-10 10:28 UTC, merged